# Generated by Django 5.2 on 2025-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('zona', models.CharField(choices=[('Centro', 'Centro'), ('Zona Norte', 'Zona Norte'), ('Zona Sul', 'Zona Sul'), ('Zona Oeste', 'Zona Oeste'), ('Toda a cidade', 'Toda a cidade')], default='Toda a cidade', max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('prioridade', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
