# Generated by Django 5.2 on 2025-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisoimportante',
            name='bairro',
        ),
        migrations.AddField(
            model_name='avisoimportante',
            name='tipo',
            field=models.CharField(choices=[('clima', 'Clima'), ('evento', 'Evento'), ('transito', 'Trânsito')], default='clima', max_length=20),
        ),
        migrations.AlterField(
            model_name='avisoimportante',
            name='zona',
            field=models.CharField(choices=[('Centro', 'Centro'), ('Zona Norte', 'Zona Norte'), ('Zona Sul', 'Zona Sul'), ('Zona Oeste', 'Zona Oeste'), ('Toda a cidade', 'Toda a cidade'), ('Av Brasil', 'Av Brasil')], default='Toda a cidade', max_length=20),
        ),
    ]
